schema_version: 1

context:
  name: pony
  version: 0.7.18
  sha256: 1fa2398b7e67b2576f32309c4e882ce796c78397062474b9ff39856bab14f6a2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pony
        - pony.orm
        - pony.utils
      python_version: ${{ python_min }}.*
about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Pony is a Python Object Relational Mapper (ORM) with beautiful query syntax.
  description: |
    Pony ORM is easy to use and powerful object-relational mapper
    for Python. Using Pony, developers can create and maintain
    database-oriented software applications faster and with less
    ffort. One of the most interesting features of Pony is its
    ability to write queries to the database using generator
    expressions. Pony then analyzes the abstract syntax tree of
    a generator and translates it to its SQL equivalent.
  homepage: https://ponyorm.com
  repository: https://github.com/ponyorm/pony
  documentation: https://docs.ponyorm.com

extra:
  recipe-maintainers:
    - dharhas
    - sdc50
    - synapticarbors
