travis:
  secure:
    BINSTAR_TOKEN: GkCi/b8bqZod+knTtlpz/XUZZUsaN/gVZJZUyKS/stMU95DzE8WI2RtJvoioKjYQ4H0Pb9FnT/DCx6CMRQ0ZC1NgwXZ8rC561Bs+ZG/palNNbI8E8dqSvragyZdDslBRT8hAi246SWSd8D1tlApUZC9DOjA5ICkr8IiNGZF24BNskPU2dV204jR1hWYFzwVRrxMiTQe5ZysCZOXiLB1l2sPS921Qcu5Q+ZeD+hR55ePMlV9zvTws6BZ2q2ITUa1IavZakjmA9Vv7amvm4Fh7JWmZWnrPemoDUZxb+nfits/j4mXrV21ujuYoMpd1+qpboKbIuac2kwL/a5g8tXlgjVhqfRcAA9g3nE/AbkDVrwL0NhNicvdz3ORdQcKDzhO4de9gkoaxBVi2SpRpC1jcYwfHMowxJTt2yXbySOwKZ+vVy7wJpGyCKXlPPehdkWFg0ycA/VGuUvfpENEGmmttCspYWW8p9mGMbFvdXJaumhxJ6HYUq8zNwnd4XwFywil7YHJZcSV/Texk5iSrVbk0h7Z+fn1hfTwUKD+0C+rHHZSo9LO8XnNzV+xt8yEUk0HLsrfM+TyipUkUUnURPaKv4SZ5huOtg8SqT2EV68Xslg/i1exFT8eJAEXXjGeQLxkjEdUvuizojHHg+I5suCvhD4M1gIQdtBW69xBkuJRP3Vo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
