travis:
  secure:
    BINSTAR_TOKEN: iaZ13L0gzk+INL3ernLKAf4pUs8PoYn8agCvDYViqqjVcV9eEsrNLPx+m4ZqVUTsLk55VbfmHHQthZGJqdfm3oZ8V9cO2In4/HD5mTu9XZNqbNKI2eLycdGKkxmCdEVv0gtPEPeDTvr0VdOzCN5VmVbbUrgp9qZ30sDjVGh8ocYg1GSximqrY2yEnyR676z0fK6npiGKTB086XzxY5Qr/ESWaa+69qvwhsikgBc1aZLhgcr6ndydm4oKRFny8JHZio5GOxXxC6u1tluLjyZhW89ZaSrF9T4ZUjCoByq608Gx5q2c57wPQD7K8Bs9/DcDkGdG9OUzNX66PhTAt4/GDERAKsqtfuNugKfb3mXnRDPfVB8hS9R65u7btv5l3D8Xp3lRs3XYZfmfM3Jc9Afc/jhGzDhGb/x82oblya3Q0RtE3NGZ45riI6xJ/yTv7CN2TjHbPpveGjwrffBlB7ubEu0Bc8AOwoATIx2Jr2id1kaTOVzBfy6cxPGE7oEhssj/F2vlkfEoKsHhJK2Y5sdcgp4TYNIQwIaK2+/cGeh9ucSelbFuA020ubW/68nj6HRfq+89sUog/X5zRR9FZkQA9zDDCDd+l++yCIMaGnJx3Bq0CyD2UDDDeFrrMQMX0ZUNclNkJdpJIUWAKrDbHAHlE5UTCY53Mv9GuUs00wmKLDI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
